### PR TITLE
Edited tags for Content Warning

### PR DESCRIPTION
**Pull request by ItzRock**
Changed the labels of some tags to be more clear what they're intended to mean and changed up the sections.

### CODE REVIEW

**Comment by ItzRock** [comment]
Opened this a bit too soon. I will re open eventually with changes.

**Comment by ItzRock** [comment]
Discussed it with the other moderators and this seems alright

**Comment by ItzRock** [comment]
> use feature branches _PLEASE_

What are you talking about? branches? You need to have write access to create branches?

**Comment by Scyye** [comment]
> What are you talking about? Branches? You need to have write access to create branches.

and you very much so do have write access to https://github.com/ItzRock/ecosystem-schema <3

**Comment by ItzRock** [comment]
> > What are you talking about? Branches? You need to have write access to create branches.
> 
> and you very much so do have write access to https://github.com/ItzRock/ecosystem-schema <3

Doesn't really change a thing in this situation ¯\_(ツ)_/¯

**Comment by Scyye** [comment]
> Doesn't really change a thing in this situation ¯_(ツ)_/¯

still, git etiquette.

**Comment by ItzRock** [comment]
Related to: https://github.com/thunderstore-io/ecosystem-schema/pull/54

**Pull request closed without merging**
