### PR TITLE
Add Sun Haven and Wilfdrost

### PR DESCRIPTION
**Pull request by Oksamies**
refs -

### CODE REVIEW

**Review by MythicManiac — APPROVED** [review]

**Comment by AugustHier** [comment]
sup

**Comment by tiffanynicoleevans-hub** [comment]
add the isle evrima verison and tribal hunter

**Comment by Brayden1213-cloud** [comment]
can you add gta 5

**Comment by alideminalisher-ship-it** [comment]
pratfall

**Comment by lucas110926-star** [comment]
add manhunt

**Comment by PedroVR20** [comment]
Can you add Infection Free Zone from Jutsu Games ?

**Comment by Colkid33** [comment]
Can You PLS! Add Ultimate Custom Night?

**Comment by AndryeaD** [comment]
Is it possible to add Descenders (made by RageSquid)?

**Comment by PowerACH** [comment]
day 1 of asking for stick it to the stickman.
pls look at this.

**Comment by PowerACH** [comment]
day 2 of asking for stick it to the stickman pls look at this.

**Pull request merged**
